### ISSUE TITLE
How to correct this

### ISSUE THREAD

**Issue by KAJOUAOU** [fluxx03/Brutforcing-Metamask-seed#1]
Traceback (most recent call last):
  File "c:\Users\Asus\Desktop\Brutforcing-Metamask-seed-main\brut2.py", line 7, in <module>
    from  etherscan import Etherscan
ImportError: cannot import name 'Etherscan' from 'etherscan' (C:\Python310\lib\site-packages\etherscan\__init__.py)
PS C:\Users\Asus\Desktop\Brutforcing-Metamask-seed-main>

**Comment by fluxxset** [comment]
Install packages frist using
pip install requriments.txt

**Comment by fluxxset** [comment]
USAGE :

    clone git repo

git clone https://github.com/fluxx03/Brutforcing-Metamask-seed.git

    install packages

cd Brutforcing-Metamask-seed

pip install -r requirements.txt

    run Script

replace your api key with XXXXXXXX in brut.py script. you can get api key from( https://etherscan.io/)

python brut.py or python3 brut.py
