### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by MadSilence88** [fluxx03/Brutforcing-Metamask-seed#2]
$ python brut.py
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\Brutforcing-Metamask-seed\brut.py", line 7, in <module>
    from  etherscan import Etherscan
ImportError: cannot import name 'Etherscan' from 'etherscan' (C:\Python\lib\site-packages\etherscan\__init__.py)

**Comment by fluxxset** [comment]
have you tried installing packages using pip if not follow this command 
`pip install -r requirements.txt`

**Comment by MadSilence88** [comment]
pip install -r requirements.txt

I did this, also tried manually installing etherscan.

Using Git Bash BTW. Windoze

**Comment by fluxxset** [comment]
what is output of this `pip install -r requirements.txt`
is it error package not found or something else ?

**Comment by fluxxset** [comment]
if its possible please share error here

**Comment by MadSilence88** [comment]
$ pip install -r requirements.txt
Collecting django
  Using cached Django-4.0.4-py3-none-any.whl (8.0 MB)
Collecting hdwallet
  Using cached hdwallet-2.1.1-py3-none-any.whl (68 kB)
Collecting etherscan
  Using cached etherscan-0.3.0-py3-none-any.whl (5.2 kB)
Collecting pyetherscan
  Using cached pyetherscan-0.1.2-py3-none-any.whl (18 kB)
Collecting etherscan-python
  Using cached etherscan_python-2.1.0-py3-none-any.whl (22 kB)
Requirement already satisfied: asgiref<4,>=3.4.1 in c:\python\lib\site-packages (from django->-r requirements.txt (line 1)) (3.5.0)
Requirement already satisfied: sqlparse>=0.2.2 in c:\python\lib\site-packages (from django->-r requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: tzdata in c:\python\lib\site-packages (from django->-r requirements.txt (line 1)) (2022.1)
Requirement already satisfied: pysha3<2,>=1.0.2 in c:\python\lib\site-packages (from hdwallet->-r requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: ecdsa<1,>=0.13 in c:\python\lib\site-packages (from hdwallet->-r requirements.txt (line 2)) (0.17.0)
Requirement already satisfied: base58<3,>=2.0.1 in c:\python\lib\site-packages (from hdwallet->-r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: mnemonic<1,>=0.19 in c:\python\lib\site-packages (from hdwallet->-r requirements.txt (line 2)) (0.20)
Requirement already satisfied: requests-cache in c:\python\lib\site-packages (from etherscan->-r requirements.txt (line 3)) (0.9.4)
Requirement already satisfied: retrying in c:\python\lib\site-packages (from pyetherscan->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: requests in c:\python\lib\site-packages (from pyetherscan->-r requirements.txt (line 4)) (2.27.1)
Requirement already satisfied: six>=1.9.0 in c:\python\lib\site-packages (from ecdsa<1,>=0.13->hdwallet->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\lib\site-packages (from requests->pyetherscan->-r requirements.txt (line 4)) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\python\lib\site-packages (from requests->pyetherscan->-r requirements.txt (line 4)) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\lib\site-packages (from requests->pyetherscan->-r requirements.txt (line 4)) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python\lib\site-packages (from requests->pyetherscan->-r requirements.txt (line 4)) (2.0.12)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in c:\python\lib\site-packages (from requests-cache->etherscan->-r requirements.txt (line 3)) (1.4.4)
Requirement already satisfied: cattrs<2.0,>=1.8 in c:\python\lib\site-packages (from requests-cache->etherscan->-r requirements.txt (line 3)) (1.10.0)
Requirement already satisfied: attrs<22.0,>=21.2 in c:\python\lib\site-packages (from requests-cache->etherscan->-r requirements.txt (line 3)) (21.4.0)
Requirement already satisfied: url-normalize<2.0,>=1.4 in c:\python\lib\site-packages (from requests-cache->etherscan->-r requirements.txt (line 3)) (1.4.3)
Installing collected packages: django, pyetherscan, hdwallet, etherscan-python, etherscan
Successfully installed django-4.0.4 etherscan-0.3.0 etherscan-python-2.1.0 hdwallet-2.1.1 pyetherscan-0.1.2

**Comment by MadSilence88** [comment]
$ python brut.py
Traceback (most recent call last):
  File "C:\Users\xxxx\Brutforcing-Metamask-seed\brut.py", line 7, in <module>
    from  etherscan import Etherscan
ImportError: cannot import name 'Etherscan' from 'etherscan' (C:\Python\lib\site-packages\etherscan\__init__.py)

**Comment by fluxxset** [comment]
that's weird it looks something like this 
https://askubuntu.com/questions/1017721/python-module-not-found-immediately-after-installing-it

**Comment by fluxxset** [comment]
solution 1 : restart pc and try again.
solution2 : try with linux subsystem

**Comment by MadSilence88** [comment]
Can it be git bash windows problem? any other better software?  or is linux virtualbox next?

**Comment by fluxxset** [comment]
i am not sure where the problem is coz it seems everything is in path also  its not git bash problem ,
no need to go for virtual box 
try with linux subsystem in windows it will work fine.

**Comment by MadSilence88** [comment]
WSL error

**Comment by MadSilence88** [comment]
File "brut.py", line 14
    MNEMONIC: str = generate_mnemonic(language="english", strength=128)
            ^
SyntaxError: invalid syntax

**Comment by MadSilence88** [comment]
Can you DM me on Telegram? <3 @fastfox88

**Comment by fluxxset** [comment]
Sure
